version: '3.8'
services:
  app:
    image: zani19/front_map:1.0.qmd
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development

  nginx:
    image: zani19/nginx_map:1.0.qmd
    ports:
      - "80:80"
    depends_on:
      - app
